CREATE USER DBAdmin identified by admin;
CREATE USER Cliente Identified by mariorossi29;
CREATE USER Impiegato identified by lacalcolatrice123;

GRANT ALL PRIVILEGES TO DBAdmin;
---- Permessi a Cliente-----
GRANT CONNECT, CREATE SESSION TO Cliente;

GRANT EXECUTE ON ANNULLAORD  TO Cliente;
GRANT EXECUTE ON CREAORD TO Cliente;
GRANT UPDATE ON PRODOTTO_ORDINE TO CLIENTE;
GRANT SELECT ON MODELLO TO CLIENTE;
GRANT SELECT ON CARATTERISTICHE_MODELLO TO CLIENTE;
GRANT SELECT ON ORDINE TO CLIENTE;
---- Permessi  a Impiegato -----
GRANT CONNECT, CREATE SESSION TO Impiegato;

GRANT SELECT, UPDATE on ORDINE TO Impiegato;
GRANT EXECUTE ON INSERTPRESENZA TO Impiegato;
GRANT EXECUTE ON INS_RAND_ORE_PRES TO Impiegato;
GRANT EXECUTE ON ASSEGNA_COMP_ASS  TO Impiegato;
GRANT EXECUTE ON ASSEGNAASS TO IMPIEGATO;
GRANT SELECT ON COMPONENTI TO Impiegato;
GRANT SELECT ON MODELLO TO IMPIEGATO;
GRANT SELECT ON CARATTERISTICHE_MODELLO TO IMPIEGATO;
